### ISSUE TITLE
No module named 'PyQt4'

### ISSUE THREAD

**Issue by Prathmesh1508** [johri002/Automatic-leaf-infection-identifier#38]
How should I install PyQt4 package??

**Comment by rnishant007** [comment]
sudo apt-get install python-qt4

**Comment by royalluckyboy** [comment]
I download PyQt4 from this web: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4
if you cannot install ver 36, I suggest you should install ver 37.
1st: Download it and paste it to desktop
2nd: open Anaconda prompt ( I use anaconda )
3rd: activate to your env you used and type: pip install (name ver of PyQt).whl
It worked for me. Good luck

**Comment by techiechaitra** [comment]
I am not able to Install PyQt4. How can I install it? I am not using Anaconda
