### ISSUE TITLE
exec(open('main.py').read())   File "<string>", line 74, in <module> ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by Prathmesh1508** [johri002/Automatic-leaf-infection-identifier#39]
exec(open('main.py').read())
  File "<string>", line 74, in <module>
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Prathmesh1508** [comment]
one more
main.py", line 74, in <module>
    ret,contours,hierarchy = cv2.findContours(bordered, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by johri002** [comment]
Make sure you are using python3 and the required version of openCv
